spring.application.name=security-tutoring

# simple way to remember a db url is :
# "protocol:driver://hosted-at:port-number/db_name" ->
# "jdbc:mysql://localhost:3306/security_db
spring.datasource.url=jdbc:mysql://localhost:3306/security_db

# As these two (and often the  - this is running locally so dw) are sensitive info,
# you may have your password and username plainly here
# however the chances of someone trying to look at this password then using it for other services you may have
# (and succeeding) is NOT zero, as we often reuse passwords

#spring-datasource.username=root
#spring.datasource.password=baggetter23

# the safer way to do this is as follows :
#   1. create an env (look at the env.example)
#   2. make these properties read the env instead
# please have a look at the POM
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


# spring knows that we are using mysql from the url we entered so no need for the driver property
spring.jpa.database=mysql
# this tells spring to create a new database at every run then delete after the run
spring.jpa.hibernate.ddl-auto=create-drop
# this shows what queries are being performed by jpa
spring.jpa.show-sql=true
